/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiJobsIndexRouteImport } from './routes/api/jobs/index'
import { Route as ApiMediaIdRouteImport } from './routes/api/media/$id'
import { Route as ApiJobsIdIndexRouteImport } from './routes/api/jobs/$id/index'
import { Route as ApiJobsIdExportRouteImport } from './routes/api/jobs/$id/export'
import { Route as ApiJobsIdFileRouteImport } from './routes/api/jobs/$id/file'
import { Route as ApiJobsIdReviewRouteImport } from './routes/api/jobs/$id/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIndexRoute = ApiJobsIndexRouteImport.update({
  id: '/api/jobs/',
  path: '/api/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdRoute = ApiMediaIdRouteImport.update({
  id: '/api/media/$id',
  path: '/api/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdIndexRoute = ApiJobsIdIndexRouteImport.update({
  id: '/api/jobs/$id/',
  path: '/api/jobs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdExportRoute = ApiJobsIdExportRouteImport.update({
  id: '/api/jobs/$id/export',
  path: '/api/jobs/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdFileRoute = ApiJobsIdFileRouteImport.update({
  id: '/api/jobs/$id/file',
  path: '/api/jobs/$id/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdReviewRoute = ApiJobsIdReviewRouteImport.update({
  id: '/api/jobs/$id/review',
  path: '/api/jobs/$id/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/status': typeof ApiStatusRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/jobs/$id/export': typeof ApiJobsIdExportRoute
  '/api/jobs/$id/file': typeof ApiJobsIdFileRoute
  '/api/jobs/$id/review': typeof ApiJobsIdReviewRoute
  '/api/jobs/$id/': typeof ApiJobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/status': typeof ApiStatusRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/jobs': typeof ApiJobsIndexRoute
  '/api/jobs/$id/export': typeof ApiJobsIdExportRoute
  '/api/jobs/$id/file': typeof ApiJobsIdFileRoute
  '/api/jobs/$id/review': typeof ApiJobsIdReviewRoute
  '/api/jobs/$id': typeof ApiJobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/status': typeof ApiStatusRoute
  '/api/media/$id': typeof ApiMediaIdRoute
  '/api/jobs/': typeof ApiJobsIndexRoute
  '/api/jobs/$id/export': typeof ApiJobsIdExportRoute
  '/api/jobs/$id/file': typeof ApiJobsIdFileRoute
  '/api/jobs/$id/review': typeof ApiJobsIdReviewRoute
  '/api/jobs/$id/': typeof ApiJobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/status'
    | '/api/media/$id'
    | '/api/jobs/'
    | '/api/jobs/$id/export'
    | '/api/jobs/$id/file'
    | '/api/jobs/$id/review'
    | '/api/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/status'
    | '/api/media/$id'
    | '/api/jobs'
    | '/api/jobs/$id/export'
    | '/api/jobs/$id/file'
    | '/api/jobs/$id/review'
    | '/api/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/api/status'
    | '/api/media/$id'
    | '/api/jobs/'
    | '/api/jobs/$id/export'
    | '/api/jobs/$id/file'
    | '/api/jobs/$id/review'
    | '/api/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiMediaIdRoute: typeof ApiMediaIdRoute
  ApiJobsIndexRoute: typeof ApiJobsIndexRoute
  ApiJobsIdExportRoute: typeof ApiJobsIdExportRoute
  ApiJobsIdFileRoute: typeof ApiJobsIdFileRoute
  ApiJobsIdReviewRoute: typeof ApiJobsIdReviewRoute
  ApiJobsIdIndexRoute: typeof ApiJobsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/': {
      id: '/api/jobs/'
      path: '/api/jobs'
      fullPath: '/api/jobs/'
      preLoaderRoute: typeof ApiJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id': {
      id: '/api/media/$id'
      path: '/api/media/$id'
      fullPath: '/api/media/$id'
      preLoaderRoute: typeof ApiMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/': {
      id: '/api/jobs/$id/'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id/'
      preLoaderRoute: typeof ApiJobsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/export': {
      id: '/api/jobs/$id/export'
      path: '/api/jobs/$id/export'
      fullPath: '/api/jobs/$id/export'
      preLoaderRoute: typeof ApiJobsIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/file': {
      id: '/api/jobs/$id/file'
      path: '/api/jobs/$id/file'
      fullPath: '/api/jobs/$id/file'
      preLoaderRoute: typeof ApiJobsIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id/review': {
      id: '/api/jobs/$id/review'
      path: '/api/jobs/$id/review'
      fullPath: '/api/jobs/$id/review'
      preLoaderRoute: typeof ApiJobsIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiMediaIdRoute: ApiMediaIdRoute,
  ApiJobsIndexRoute: ApiJobsIndexRoute,
  ApiJobsIdExportRoute: ApiJobsIdExportRoute,
  ApiJobsIdFileRoute: ApiJobsIdFileRoute,
  ApiJobsIdReviewRoute: ApiJobsIdReviewRoute,
  ApiJobsIdIndexRoute: ApiJobsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
